"""datetime

Revision ID: 3ba62af84ff0
Revises: 5be6d03fb266
Create Date: 2025-07-09 15:41:36.586401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ba62af84ff0'
down_revision: Union[str, Sequence[str], None] = '5be6d03fb266'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('createdAt', sa.DateTime(), nullable=False))
    op.add_column('notifications', sa.Column('updatedAt', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('createdAt', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('updatedAt', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updatedAt')
    op.drop_column('users', 'createdAt')
    op.drop_column('notifications', 'updatedAt')
    op.drop_column('notifications', 'createdAt')
    # ### end Alembic commands ###
