"""notification

Revision ID: 5be6d03fb266
Revises: 156fd30e1227
Create Date: 2025-07-09 15:22:40.734946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5be6d03fb266'
down_revision: Union[str, Sequence[str], None] = '156fd30e1227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('userId', sa.Integer(), nullable=False))
    op.add_column('notifications', sa.Column('shortMessage', sa.String(length=20), nullable=False))
    op.create_foreign_key(None, 'notifications', 'users', ['userId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'shortMessage')
    op.drop_column('notifications', 'userId')
    # ### end Alembic commands ###
